version: 2
jobs:
  build:
    working_directory: ~/nabbitmq
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: unit tests
          command: 'node node_modules/mocha/bin/_mocha --require ts-node/register --ui bdd test/unit/*.spec.ts'
